// Mocks generated by Mockito 5.4.6 from annotations
// in tootfruit/test/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/cupertino.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tootfruit/interfaces/i_audio_player.dart' as _i5;
import 'package:tootfruit/interfaces/i_storage_repository.dart' as _i7;
import 'package:tootfruit/interfaces/i_toot_repository.dart' as _i8;
import 'package:tootfruit/interfaces/i_user_repository.dart' as _i9;
import 'package:tootfruit/models/toot.dart' as _i2;
import 'package:tootfruit/models/user.dart' as _i3;
import 'package:tootfruit/services/navigation_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeToot_1 extends _i1.SmartFake implements _i2.Toot {
  _FakeToot_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_2 extends _i1.SmartFake implements _i3.User {
  _FakeUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_3<T extends _i4.State<_i4.StatefulWidget>>
    extends _i1.SmartFake
    implements _i4.GlobalKey<T> {
  _FakeGlobalKey_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigatorState_4 extends _i1.SmartFake
    implements _i4.NavigatorState {
  _FakeNavigatorState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [IAudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAudioPlayer extends _i1.Mock implements _i5.IAudioPlayer {
  MockIAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Duration> setAudio(String? assetPath) =>
      (super.noSuchMethod(
            Invocation.method(#setAudio, [assetPath]),
            returnValue: _i6.Future<Duration>.value(
              _FakeDuration_0(this, Invocation.method(#setAudio, [assetPath])),
            ),
          )
          as _i6.Future<Duration>);

  @override
  void play() => super.noSuchMethod(
    Invocation.method(#play, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIStorageRepository extends _i1.Mock
    implements _i7.IStorageRepository {
  MockIStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> exists(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [key]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<T?> get<T>(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i6.Future<T?>.value(),
          )
          as _i6.Future<T?>);

  @override
  _i6.Future<void> set(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#set, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ITootRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITootRepository extends _i1.Mock implements _i8.ITootRepository {
  MockITootRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Toot> getAllToots() =>
      (super.noSuchMethod(
            Invocation.method(#getAllToots, []),
            returnValue: <_i2.Toot>[],
          )
          as List<_i2.Toot>);

  @override
  _i2.Toot getTootByFruit(String? fruit) =>
      (super.noSuchMethod(
            Invocation.method(#getTootByFruit, [fruit]),
            returnValue: _FakeToot_1(
              this,
              Invocation.method(#getTootByFruit, [fruit]),
            ),
          )
          as _i2.Toot);
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i9.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.User> loadUser() =>
      (super.noSuchMethod(
            Invocation.method(#loadUser, []),
            returnValue: _i6.Future<_i3.User>.value(
              _FakeUser_2(this, Invocation.method(#loadUser, [])),
            ),
          )
          as _i6.Future<_i3.User>);

  @override
  _i6.Future<void> saveUser(_i3.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateCurrentFruit(String? fruit) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentFruit, [fruit]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i10.NavigationService {
  MockNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GlobalKey<_i4.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_3<_i4.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i4.GlobalKey<_i4.NavigatorState>);

  @override
  _i4.NavigatorState get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeNavigatorState_4(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i4.NavigatorState);
}
